name: Torder CEO PR CI Workflow

# Trigger the workflow for pull requests
on:
  pull_request:
    # No 'branches' specified, applies to all branches

# Define jobs
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 선택한 branch or tag 체크아웃
      - name: check out branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # pnpm 설치
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      # 노드 버전 세팅
      - name: setup node version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "pnpm"

      # Install dependencies (npm example)
      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      # Run tests
      # - name: Run tests
      #   run: pnpm test

      # Optionally build the project (if needed)
      - name: Build project
        run: pnpm build
